# Generated by Django 4.2.18 on 2025-02-17 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0003_pessoa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alunos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('matricula', models.CharField(max_length=50)),
                ('curso', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('data_emprestimo', models.DateField(max_length=50)),
                ('data_devolucao', models.DateField(max_length=50)),
                ('id_aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='alunos.alunos')),
            ],
        ),
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_publicação', models.DateField(max_length=50)),
                ('titulo', models.CharField(max_length=50)),
                ('autor', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='cidade',
        ),
        migrations.DeleteModel(
            name='Cidade',
        ),
        migrations.DeleteModel(
            name='Estado',
        ),
        migrations.DeleteModel(
            name='Pessoa',
        ),
        migrations.AddField(
            model_name='emprestimos',
            name='id_livro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='alunos.livros'),
        ),
    ]
